# SPDX-License-Identifier: MIT
#
# 缓存清理：定期清理 GitHub Actions 缓存
# 参考 OpenWRT-CI 的 Cache-Clean.yml
name: Cache-Clean

on:
  #自动清理：每周一早上4点(北京时间)
  schedule:
    - cron: 0 20 * * 0
  #手动清理
  workflow_dispatch:

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Projects
        uses: actions/checkout@v4

      - name: Cache Clean 删除全部缓存
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh cache list --limit 100 --json id | jq -r '.[].id' | xargs -I {} gh cache delete {}
